# Generated by Django 5.2.10 on 2026-01-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_address_id_alter_coupon_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('huiles', 'Huiles Essentielles'), ('meditation', 'Méditation'), ('tisanes', 'Tisanes & Infusions'), ('yoga', 'Yoga'), ('aromatherapie', 'Aromathérapie'), ('naturopathie', 'Naturopathie')], max_length=20),
        ),
    ]
