# Generated by Django 5.2.10 on 2026-01-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('NO', 'Nouveau'), ('PO', 'Populaire'), ('ES', 'Essentiel')], max_length=20),
        ),
    ]
